import logging
from core.settings import settings

logger = logging.getLogger(__name__)

# --- Configuration ---
GEMINI_API_KEY = settings.GEMINI_API_KEY
EMAIL_SENDER = settings.EMAIL_SENDER
EMAIL_PASSWORD = settings.EMAIL_PASSWORD
EMAIL_HOST = settings.EMAIL_HOST
EMAIL_PORT = settings.EMAIL_PORT
GRAFANA_URL = settings.GRAFANA_URL
GRAFANA_USERNAME = settings.GRAFANA_USERNAME
GRAFANA_TOKEN = settings.GRAFANA_TOKEN
GRAFANA_DASHBOARD_URL = settings.GRAFANA_DASHBOARD_URL
GRAFANA_PROMETHEUS_DATASOURCE_ID = settings.GRAFANA_PROMETHEUS_DATASOURCE_ID
SLACK_WEBHOOK_URL = settings.SLACK_WEBHOOK_URL

# Jira
JIRA_BASE_URL = settings.JIRA_BASE_URL
JIRA_USER = settings.JIRA_USER
JIRA_API_TOKEN = settings.JIRA_API_TOKEN
JIRA_PROJECT_KEY = settings.JIRA_PROJECT_KEY

# Other mock integrations
GRAFANA_ONCALL_WEBHOOK_URL = settings.GRAFANA_ONCALL_WEBHOOK_URL
OPSGENIE_API_KEY = settings.OPSGENIE_API_KEY
PAGERDUTY_ROUTING_KEY = settings.PAGERDUTY_ROUTING_KEY
EMAIL_RECIPIENTS = settings.email_recipients_list

WEBHOOK_SECRET = settings.WEBHOOK_SECRET

# Kafka Settings
KAFKA_BOOTSTRAP_SERVERS = settings.KAFKA_BOOTSTRAP_SERVERS
KAFKA_INCIDENT_TOPIC = settings.KAFKA_INCIDENT_TOPIC
KAFKA_CONSUMER_GROUP = settings.KAFKA_CONSUMER_GROUP
KAFKA_DLQ_TOPIC = settings.KAFKA_DLQ_TOPIC
USE_KAFKA_QUEUE = settings.USE_KAFKA_QUEUE
